### ISSUE TITLE
HI,I run your script, but return a error

### ISSUE THREAD

**Issue by cyhatgithub** [Azure-Samples/storage-table-python-getting-started#3]
When I run the code, it return a "NotImplemented" error messge, but I don't know why.

**Comment by yaronyg** [comment]
Could you please give the list of commands you used to clone the sample, run pip, set up the config and run the test? Because I just followed the read me with a fresh clone of the depot and it ran without problem. Also what platform are you running on? Windows? Linux? Mac?

**Comment by cyhatgithub** [comment]
I'm sorry that the question is not described clearly.
emmm...I looked at the document of azure and found that I had fewer parameters.
Thank you for your reply。

**Comment by yaronyg** [comment]
No problem.
